title: Floanter
# 左侧栏名字
author_name: Floanter.

# 左侧栏标签，只能两个
tag1: Uno
tag2: Dos

# 左侧栏Github连接
github_url: https://github.com/Floanter

# 左侧栏座右铭，分两句
motto_prev: “Soy prisionero del tiempo que va, un pasajero de la eternidad.”

# 小站部署日期（运营时间）
public_date: 2022-02-16

# Menu
menu:
  - [Inicio, '/', 'icon-shouye']
  - [Log, '/archives', 'icon-rizhi']
  - [Link, '/link', 'icon-youqinglianjie']
  - ['Sobre Mi', '/about', 'icon-guanyuwomen']
  - ['Tools', '/tools', 'icon-gongju']

# Enlace de amistad: avatar, nombre, enlace.
links:
 - ['https://d33wubrfki0l68.cloudfront.net/6657ba50e702d84afb32fe846bed54fba1a77add/827ae/logo.svg', 'Hexo.', 'https://hexo.io/zh-cn/']

# Anuncios en la columna derecha
notice: Hola! espero que te lo pases bien en mi blog y te sea util.

# Lista de música a la derecha: título de la canción, autor, enlace, portada.
musics:
  - ['安河桥', '宋冬野', 'http://ting6.yymp3.net:82/new25/songdongye/11.mp3', 'https://img2.baidu.com/it/u=1260056724,1076343118&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=500']
  - ['卡布达', '暂无', '/music/kabuda.mp3', 'https://img2.baidu.com/it/u=705831265,2862720033&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=500']
  - ['八连杀', '苏三', '/music/八连杀.mp3', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo0SWQx6YrNA8lElaG4OOKLkNkNzLO1PflKg&usqp=CAU']

# auto presentación.
likes:
  - Nombre：Brian Flores.
  - Edad：25
  - Sexo：♂
  - Ciudad：Juarez
  - 现居住地：四川省成都市武侯区
  - 职业：Web前端开发
  - 喜欢：打游戏，游泳，下象棋

# Configuración de la herramienta: portada, título, introducción, enlace.
tools:
  - ['https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/30e94204580a4dbd83a64d4f91a9a6e5~tplv-k3u1fbpfcp-no-mark:240:240:240:160.awebp?', 'PNG图片压缩器', '这是一款无损压缩PNG图片的在线工具，可以童工上传或拖动来批量压缩图片并打包下载', 'http://1.14.43.39:5000/']

# Información del sitio web de la columna derecha.
copyright: © Brian Flores 2023 - 2023. All rights reserved


# Ya sea para abrir los comentarios del artículo Valine:https://valine.js.org/configuration.htm
comments:
  enable: true
  appId: 'Pf8zCXGEH1qsprnWfikVVujL-gzGzoHsz'
  appKey: 'qOqoiUHhH1TGtLRUYURkLRQX'
  placeholder: 'Por favor deje sus valiosos comentarios'
  meta: ['nick']
  recordIP: true
  visitor: true
  enableQQ: true

# Ya sea para habilitar el método de carga CDN de recursos estáticos.
static_load_type: local

# patrón conmemorativo. none: no establecido. all：gris todo. index: página de inicio gris.
gray: none

  # Oculto después de que el registro supera los 1000 caracteres.（La altura máxima es: 1000px)，1000 puede ser cualquier valor.
log_text_num: 1000

# número de versión.
version: 1.0.2
